// HERMETIC COMMERCE CATALOG — a build harness, never production code.
//
// WHY IT EXISTS. Sealing the COMMERCE canonical fingerprint means building the
// page with every commerce surface actually rendered: a real variant selector,
// a live sticky add-to-cart, prices, a default variant. That state is normally
// reached only by calling Shopify at build time.
//
// The question being asked is about STRUCTURE, not about integration, so the
// answer must not depend on live credentials — a fingerprint that can only be
// regenerated by whoever holds a production token is not a lock anyone can
// verify. This module supplies the exact shape `getProductCommerce()` returns,
// with no network and no secrets.
//
// WHY AN ALIAS AND NOT A FLAG. Adding a third branch to lib/shopify/catalog.ts
// — "preview | shopify | fixture" — would put a fake-data path inside the code
// that ships, one env var away from a real deployment serving invented prices.
// astro.config.commerce-fixture.mjs swaps this module in at BUILD time
// instead, so production has no idea it exists.
//
// It lives in test-fixtures/ deliberately: generate-landing.mjs's copyTemplate
// already excludes that directory, so no generated landing can inherit it.
//
// The values are obviously synthetic (`gid://fixture/...`, round prices) so
// nothing here can ever be mistaken for real catalogue data.
import type { ProductCommerce } from '@/lib/shopify/types';

// A RELATIVE path, not the alias: under this config `@/lib/shopify/catalog`
// resolves to THIS file, so the alias form is a self-referencing re-export and
// rolldown rejects it outright ([CIRCULAR_REEXPORT]). These two are pure
// string helpers with no Shopify dependency, so the real ones are reused
// rather than duplicated — a second copy could drift from the titles the
// production build actually renders.
export { parseProjectionCount, toCustomerTitle } from '../src/lib/shopify/catalog';

/**
 * Three variants, one of them sold out.
 *
 * The sold-out one is not decoration: it is the only way the selector renders
 * its unavailable branch, and a canonical structure that never exercised that
 * branch would be a structure nobody had actually measured.
 */
const FIXTURE: ProductCommerce = {
  handle: 'fixture-product',
  title: 'Producto de fixture',
  currencyCode: 'EUR',
  optionName: 'Opciones',
  variants: [
    {
      id: 'gid://fixture/ProductVariant/1',
      title: '1 proyección',
      projectionCount: 1,
      optionValue: '1 Slide',
      availableForSale: true,
      unitPriceCents: 1900,
      unitCompareAtCents: 2900,
      imageIndex: 0,
    },
    {
      id: 'gid://fixture/ProductVariant/6',
      title: '6 proyecciones',
      projectionCount: 6,
      optionValue: '6 Slides',
      availableForSale: true,
      unitPriceCents: 2900,
      unitCompareAtCents: 3900,
      imageIndex: 1,
    },
    {
      id: 'gid://fixture/ProductVariant/24',
      title: '24 proyecciones',
      projectionCount: 24,
      optionValue: '24 Slides',
      availableForSale: false,
      unitPriceCents: 3900,
      unitCompareAtCents: null,
      imageIndex: null,
    },
  ],
  // The 6-variant, matching catalog.ts's PREFERRED_DEFAULT_PROJECTIONS.
  defaultVariantId: 'gid://fixture/ProductVariant/6',
  anyAvailable: true,
  images: [
    { url: 'https://fixture.invalid/1.jpg', altText: 'Fixture 1', width: 1200, height: 1200 },
    { url: 'https://fixture.invalid/2.jpg', altText: 'Fixture 2', width: 1200, height: 1200 },
  ],
};

export function getProductCommerce(): Promise<ProductCommerce> {
  return Promise.resolve(FIXTURE);
}

export function resolveCommerceMode(): 'preview' | 'shopify' {
  return 'shopify';
}

export function resolveProductHandle(): string {
  return FIXTURE.handle;
}
