// STRUCTURAL FINGERPRINT — the invariant that makes "Fixed AstraVibe" fixed.
//
// Two landings generated by this repo must be the SAME PAGE with different
// product data in it. Not "similar", not "the same blocks": structurally
// identical. This module reduces rendered HTML to the part that must never
// vary and hashes it, so the claim is a test rather than an intention.
//
//   structuralFingerprint(htmlA).hash === structuralFingerprint(htmlB).hash
//
// WHY NOT JUST "DON'T RUN THE DESIGN AGENT". Because that is a promise about
// a flag, and a flag is not an invariant. Anyone can add a section, reorder
// two, or widen a container by hand, and nothing would notice. The fingerprint
// notices.
//
// PURE STRING WORK, NO DEPENDENCIES, NO DOM. admin/test runs its contract
// suites under vitest's `server` project, which is the plain `node`
// environment — there is no document there to parse into, and adding a parser
// dependency to satisfy a test is exactly the kind of thing agents.MD forbids.
// Astro emits well-formed markup, so a tokenizer is enough; content-contract
// .mjs sets the same precedent of a dependency-free contract module.
//
// ---------------------------------------------------------------------------
// THE CENTRAL DESIGN DECISION: CLASSES ARE NOT NORMALIZED. ALL OF THEM SURVIVE.
// ---------------------------------------------------------------------------
//
// The obvious-looking rule — "strip any class that carries a colour, because
// palette varies per product" — is WRONG here, and it is wrong in the most
// dangerous direction: it produces a false PASS. It cannot distinguish
// `bg-grape` (would be stripped) from `bg-white`, and a regex loose enough to
// catch colour words is loose enough to eat `bg-gradient-to-r`, which is
// layout.
//
// It is also unnecessary, and that is the real point. In this template the
// palette lives in CSS custom properties inside the `@theme` block of
// global.css — `--color-grape: #7C3AED`. Per-product recolouring rewrites
// THOSE VALUES. It does not rewrite the markup: `class="bg-grape"` is
// byte-identical in every product, because the token name never changes, only
// what it resolves to. The palette is simply not present in the HTML.
//
// So colour reaches the HTML through exactly two doors, and those are the only
// two this module closes: hex/rgb literals inside `style` attributes, and the
// same literals inside inline SVG paint attributes. Everything else about a
// class attribute — spacing, widths, grid, breakpoints, order, every
// responsive variant — is kept and compared.
//
// ---------------------------------------------------------------------------

import { createHash } from 'node:crypto';

/**
 * Attribute values that carry PRODUCT DATA rather than structure. The
 * attribute's presence is structural and is kept; its value is dropped.
 *
 * `href` is here because a link's destination is product/merchant data (a
 * Shopify handle, a legal page slug), while the fact that a link exists at
 * that position is structure. Same reasoning for every entry: keep the slot,
 * drop what is in it.
 */
export const VALUE_DROPPED_ATTRS = new Set([
  'href',
  'src',
  'srcset',
  'poster',
  'alt',
  'title',
  'content', // <meta content="..."> — description, og:*, theme-color
  'value',
  'placeholder',
  'aria-label',
  'aria-describedby',
  // `aria-labelledby` is NOT here any more. Its value is a REFERENCE — it names
  // the element that labels this one — and a reference is a relation, which is
  // structure. Dropping it meant a panel pointing at the wrong trigger, or at
  // nothing, hashed exactly like a correct one. Every value in this template is
  // either a static literal (`checkout-shipping-title`, `cookie-banner-title`)
  // or a FAQ trigger id, and the latter is made positional-independent by the
  // relational pass below rather than by throwing the relation away.
  'datetime',
  'download',
  'style', // handled specially below — declarations survive, values are filtered
]);

/**
 * Attributes dropped ENTIRELY, name included, because they are build-identity
 * rather than page structure.
 *
 * Astro stamps every island with a `uid` and content-hashed `component-url` /
 * `renderer-url`, and serialises the island's props into `props`. All four
 * change when the product changes or merely when the bundle is rebuilt.
 * `component-export` is deliberately NOT here: WHICH island is mounted at a
 * position is structure, and swapping CartDrawer for something else must fail.
 *
 * `prefix` joined them after an audit, not because it broke a hash. It is
 * Astro's per-render island counter (`r9`, `r10`, …): DETERMINISTIC — two
 * identical builds produce identical prefixes, verified by building twice —
 * but it renumbers when an earlier island appears or disappears, so a preview
 * build and a commerce build disagree on it for every island after the first
 * difference. It encodes render ORDER and nothing else, and order is already
 * carried by the skeleton's own sequence plus `component-export`. Dropping it
 * therefore hides no composition: a moved, swapped or removed island still
 * fails. See the control test in contract.fixed-fingerprint.test.ts.
 */
export const FULLY_DROPPED_ATTRS = new Set([
  'uid',
  'prefix',
  'props',
  'component-url',
  'renderer-url',
  'ssr',
  'opts',
  'integrity',
  'nonce',
]);

/**
 * The media-slot signature, from ui/Media.astro.
 *
 * That component renders `<video>` when the product has a video for the slot
 * and `<img>` when it has a still, and BOTH carry this exact class triple plus
 * the same inline `aspect-ratio`. The slot's geometry is therefore already
 * invariant by construction — only the tag differs.
 *
 * Per the Fixed contract, "same visual slot geometry, adaptable media" means a
 * product with video and a product without must not be called structurally
 * different. So inside this signature the tag name collapses to MEDIA. The
 * aspect-ratio style is NOT collapsed: that IS the geometry, and a slot that
 * changes shape between products is a real regression.
 *
 * Scoped deliberately tight. An `<img>` anywhere else in the page is still
 * compared as an `<img>`, so a stray image added to a section still fails.
 */
export const MEDIA_SLOT_CLASSES = ['h-full', 'w-full', 'object-cover'];
const MEDIA_SLOT_TAGS = new Set(['img', 'video', 'picture', 'source']);

/**
 * Attributes that exist only because of WHICH media kind filled the slot, and
 * are therefore dropped name-and-all inside one.
 *
 * Collapsing the tag to MEDIA is not enough on its own: `<img>` brings `alt`
 * and `sizes`, `<video>` brings `poster`, `muted`, `loop` and friends, so two
 * slots holding the same geometry would still differ by the mere PRESENCE of
 * those names. That is the media kind leaking back in through the attribute
 * list, and it would fail a product whose only sin is having a video where
 * AstraVibe had a still.
 *
 * Scoped to media slots only. Outside one, `loading` and `decoding` stay
 * comparable, because there they describe a decision someone made about a
 * specific image rather than the shape of a slot.
 */
const MEDIA_SLOT_KIND_ATTRS = new Set([
  'alt', 'poster', 'sizes', 'widths', 'loading', 'decoding',
  'muted', 'loop', 'playsinline', 'autoplay', 'preload', 'controls', 'type',
]);

/**
 * `style` declarations whose VALUE is product data rather than geometry.
 *
 * Exactly one entry, and it earns its place: 13-real-results.astro draws each
 * rating bar as `style="width:{pct}%"`, so the number is a review statistic.
 * Every other inline declaration keeps its value, which is why an inline
 * `padding:12px` that appears in one product and not the other still fails.
 */
const DYNAMIC_STYLE_PROPS = new Set(['width']);

const VOID_TAGS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'param', 'source', 'track', 'wbr',
]);

/** Tags whose text content is never page structure. */
const RAW_TEXT_TAGS = new Set(['script', 'style', 'template', 'noscript']);

const COLOUR_LITERAL = /#[0-9a-f]{3,8}\b|\b(?:rgba?|hsla?|oklch|color-mix)\([^)]*\)/gi;

/** Collapses colour literals so a repaint never moves the fingerprint. */
function stripColours(value) {
  return value.replace(COLOUR_LITERAL, '<colour>');
}

/**
 * Reduces a `style` attribute to its declarations, keeping property names and
 * geometry values while removing colour and the one dynamic numeric property.
 */
function normalizeStyle(value) {
  return value
    .split(';')
    .map((decl) => decl.trim())
    .filter(Boolean)
    .map((decl) => {
      const colon = decl.indexOf(':');
      if (colon === -1) return decl;
      const prop = decl.slice(0, colon).trim().toLowerCase();
      const raw = decl.slice(colon + 1).trim();
      if (DYNAMIC_STYLE_PROPS.has(prop)) return `${prop}:<n>`;
      return `${prop}:${stripColours(raw)}`;
    })
    .sort() // declaration order is not layout
    .join(';');
}

/**
 * Astro island ids and Vite-hashed anchors are build identity. Page anchors —
 * #buy, #faq, #garantia, #como-funciona — are structure a reader can link to,
 * and losing one must fail.
 *
 * The rule is shape-based rather than a hardcoded anchor list, so a template
 * that adds a new anchor does not need this module edited: an id that is a
 * long unbroken hash-looking run is build output; anything with a hyphen or
 * short enough to be hand-written is an anchor.
 */
function normalizeId(value) {
  return /^[A-Za-z0-9_]{10,}$/.test(value) && /\d/.test(value) ? '<uid>' : value;
}

/** `class="b  a"` and `class="a b"` are the same styling; sort so they hash alike. */
function normalizeClass(value) {
  return value.split(/\s+/).filter(Boolean).sort().join(' ');
}

/**
 * Walks the raw markup and emits one line per element, indented by depth.
 * Text nodes, comments and doctype never appear: copy is the most dynamic
 * thing on the page.
 */
export function structuralSkeleton(html) {
  const lines = [];
  let depth = 0;
  let i = 0;

  while (i < html.length) {
    const lt = html.indexOf('<', i);
    if (lt === -1) break;

    // comment / doctype / CDATA — never structure
    if (html.startsWith('<!', lt)) {
      const end = html.indexOf('>', lt);
      i = end === -1 ? html.length : end + 1;
      continue;
    }

    const gt = findTagEnd(html, lt);
    if (gt === -1) break;
    const rawTag = html.slice(lt + 1, gt);
    i = gt + 1;

    if (rawTag.startsWith('/')) {
      depth = Math.max(0, depth - 1);
      continue;
    }

    const selfClosing = rawTag.endsWith('/');
    const tagBody = selfClosing ? rawTag.slice(0, -1) : rawTag;
    const nameMatch = /^([a-zA-Z][\w:-]*)/.exec(tagBody);
    if (!nameMatch) continue;

    const tag = nameMatch[1].toLowerCase();
    const attrs = parseAttrs(tagBody.slice(nameMatch[1].length));

    lines.push('  '.repeat(depth) + renderElement(tag, attrs));

    // Raw-text elements: skip to the matching close so their body is never
    // mistaken for markup. A `<script>` containing `<div>` is not a div.
    if (RAW_TEXT_TAGS.has(tag) && !selfClosing) {
      const close = html.toLowerCase().indexOf(`</${tag}`, i);
      i = close === -1 ? html.length : close;
      continue;
    }

    if (!selfClosing && !VOID_TAGS.has(tag)) depth += 1;
  }

  return lines.join('\n');
}

/** Finds the `>` that closes a tag, ignoring any inside a quoted value. */
function findTagEnd(html, start) {
  let quote = null;
  for (let j = start + 1; j < html.length; j += 1) {
    const ch = html[j];
    if (quote) {
      if (ch === quote) quote = null;
    } else if (ch === '"' || ch === "'") {
      quote = ch;
    } else if (ch === '>') {
      return j;
    }
  }
  return -1;
}

/** `name="v" flag name='v'` → ordered [name, value] pairs; bare flags get ''. */
function parseAttrs(source) {
  const attrs = [];
  const re = /([a-zA-Z_:@][\w:.@-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    attrs.push([m[1].toLowerCase(), m[2] ?? m[3] ?? m[4] ?? '']);
  }
  return attrs;
}

function renderElement(tag, attrs) {
  const classAttr = attrs.find(([name]) => name === 'class');
  const classes = classAttr ? classAttr[1].split(/\s+/).filter(Boolean) : [];

  const isMediaSlot =
    MEDIA_SLOT_TAGS.has(tag) && MEDIA_SLOT_CLASSES.every((c) => classes.includes(c));

  const parts = [];
  for (const [name, value] of attrs) {
    if (FULLY_DROPPED_ATTRS.has(name)) continue;
    if (isMediaSlot && MEDIA_SLOT_KIND_ATTRS.has(name)) continue;
    if (name === 'class') {
      parts.push(`class="${normalizeClass(value)}"`);
    } else if (name === 'id') {
      parts.push(`id="${normalizeId(value)}"`);
    } else if (name === 'style') {
      parts.push(`style="${normalizeStyle(value)}"`);
    } else if (VALUE_DROPPED_ATTRS.has(name)) {
      parts.push(name);
    } else if (name === 'fill' || name === 'stroke') {
      parts.push(`${name}="${stripColours(value)}"`);
    } else {
      parts.push(value === '' ? name : `${name}="${value}"`);
    }
  }

  parts.sort(); // attribute order is not structure
  return `<${isMediaSlot ? 'MEDIA' : tag}${parts.length ? ' ' + parts.join(' ') : ''}>`;
}


// ---------------------------------------------------------------------------
// REPEATABLE AND OPTIONAL REGIONS — structural GRAMMAR, not rendered instance.
// ---------------------------------------------------------------------------
//
// THE PROBLEM THIS SOLVES. A gallery with four images and a gallery with eight
// are the same design. The skeleton disagreed, because it recorded one line per
// rendered element, so element COUNT — which follows array LENGTH — was being
// compared as if it were layout. Two products of the same template could never
// hash alike unless their data happened to be the same size.
//
// WHAT IT IS NOT. There is no heuristic here: nothing detects "similar
// siblings" and collapses them. A region is normalized ONLY if an explicit
// entry in the grammar names its wrapper, and only into the item shapes that
// entry declares. A blanket sibling-collapse would hide the regressions this
// module exists to catch.
//
// THE EMISSION IS THE DECLARATION, NOT THE OBSERVATION. A region emits every
// shape its grammar declares, sorted, whether or not this particular build
// rendered one. That is what lets a product whose variants are all in stock
// hash identically to one with a sold-out variant: both use the same grammar,
// and WHICH states occurred is data. Coverage of the declared shapes is proved
// separately, by tests that materialize each one — see the state-coverage
// suite. A shape nobody can produce must not sit in the grammar unexercised.
//
// THREE THINGS KEEP IT SAFE:
//
//   1. The WRAPPER's own line is emitted exactly as before. Change its classes,
//      its grid, its breakpoint or its role and the hash moves — only its
//      CHILDREN are abstracted.
//   2. An item whose sub-skeleton is not among the declared shapes is emitted
//      VERBATIM. Changed card markup, a new child type or a swapped component
//      therefore still fails, loudly.
//   3. A region declared `min` that renders fewer items emits a distinct
//      marker, so an empty wrapper never hashes as a full one.
//
// OPTIONAL regions work the same way and answer a different question: a slot
// the template declares may legitimately not materialize, because a capability
// is absent. `OPTIONAL<Shape>` says the template HAS that slot. Whether this
// product filled it is a capability fact, reported separately and never folded
// into this hash. Absence is only ever normalized for a registered optional
// region — a section that vanishes without one is still a failure.

/** Splits a skeleton into `[line, depth]` pairs. Indent is two spaces per level. */
function parseLines(skeleton) {
  return skeleton.split('\n').filter(Boolean).map((line) => {
    const body = line.replace(/^ +/, '');
    return { text: body, depth: (line.length - body.length) / 2 };
  });
}

/** The direct-child blocks of the element at `index`, each as `[from, to)`. */
function childBlocks(lines, index) {
  const parentDepth = lines[index].depth;
  const blocks = [];
  let i = index + 1;
  while (i < lines.length && lines[i].depth > parentDepth) {
    if (lines[i].depth === parentDepth + 1) {
      const start = i;
      i += 1;
      while (i < lines.length && lines[i].depth > parentDepth + 1) i += 1;
      blocks.push([start, i]);
    } else {
      i += 1;
    }
  }
  return blocks;
}

/**
 * A child block rendered as its own skeleton, re-indented from zero.
 *
 * `relationalIds` is opted into per region: only where an item legitimately
 * carries its own DOM identity does the ordinal get canonicalized away.
 */
function blockSkeleton(lines, [from, to], { relationalIds = false } = {}) {
  const base = lines[from].depth;
  const rows = lines.slice(from, to).map((l) => '  '.repeat(l.depth - base) + l.text);
  return (relationalIds ? canonicalizeItemIdentity(rows) : rows).join('\n');
}

/**
 * Does this element line satisfy a grammar entry's wrapper matcher?
 *
 * EXPORTED, purely additively — this was private until Validation needed to
 * ask the SAME question `applyGrammar` asks internally ("is this region's
 * wrapper present on the page at all") from OUTSIDE the collapse pass, for
 * collectUncollapsedRegions() below. No behaviour here changed; only the
 * binding's visibility did.
 */
export function matchesWrapper(text, wrapper) {
  if (!text.startsWith(`<${wrapper.tag}`) && wrapper.tag !== '*') return false;
  for (const cls of wrapper.classes ?? []) {
    // Classes are sorted and space-joined by normalizeClass, so a word-boundary
    // test is exact without depending on their order.
    if (!new RegExp(`(^|[" ])${cls.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}([" ]|$)`).test(text)) return false;
  }
  for (const [name, value] of Object.entries(wrapper.attrs ?? {})) {
    if (!text.includes(value === true ? ` ${name}` : ` ${name}="${value}"`)) return false;
  }
  // EXACT CLASS SET, opt-in. `classes` asks "does it carry these"; a Tailwind
  // page has many elements carrying any one utility, so a class like
  // `bg-grape-tint` matches both a section wrapper and a table cell that
  // happens to share the colour. Where a slot needs to name ONE element and no
  // attribute distinguishes it, this asks "is this class list exactly that".
  //
  // Additive: no V1 declaration sets it, so nothing about V1's matching or its
  // rendered artifact changes.
  if (wrapper.exactClasses) {
    const found = /class="([^"]*)"/.exec(text)?.[1] ?? '';
    const want = [...wrapper.exactClasses].sort().join(' ');
    if (found.split(' ').filter(Boolean).sort().join(' ') !== want) return false;
  }
  return true;
}

/**
 * Rewrites DOM identity RELATIONALLY inside one repeated item.
 *
 * An accessible accordion needs a unique id per panel and per trigger, so its
 * items are structurally unique by construction: `faq-panel-0`, `faq-panel-1`,
 * … Every item became its own shape and REPEAT could collapse nothing.
 *
 * The ordinal is not design. The RELATIONSHIP is. So every id declared inside
 * one item is numbered by first appearance WITHIN THAT ITEM, and every
 * reference to one — `aria-controls`, `aria-labelledby` — is rewritten to the
 * same symbol. Item 0 and item 6 then hash alike, while:
 *
 *   - a reference pointing at ANOTHER item's id is not in this item's map, so
 *     it survives as a raw value and the shape stops matching: cross-links fail
 *   - a missing id, a missing aria-controls or a missing aria-labelledby
 *     changes the attribute list: absence fails
 *   - a swapped relationship (trigger pointing at its own id) maps to a
 *     different symbol than the panel expects: it fails
 *
 * GLOBAL id UNIQUENESS is deliberately NOT this function's job — two items
 * carrying the same id each canonicalize within their own block and would hash
 * alike. That is asserted directly, on the rendered HTML, by the accessibility
 * contract, which is the right instrument for it.
 */
function canonicalizeItemIdentity(itemLines) {
  const symbols = new Map();
  for (const line of itemLines) {
    const m = /\sid="([^"]*)"/.exec(line);
    if (m && !symbols.has(m[1])) symbols.set(m[1], `<item-ref-${symbols.size + 1}>`);
  }
  if (symbols.size === 0) return itemLines;

  return itemLines.map((line) =>
    line.replace(/\s(id|aria-controls|aria-labelledby)="([^"]*)"/g, (whole, attr, value) =>
      symbols.has(value) ? ` ${attr}="${symbols.get(value)}"` : whole,
    ),
  );
}

/**
 * Rewrites declared regions into their grammar. Returns the skeleton unchanged
 * when no grammar is supplied, so every existing caller keeps its behaviour.
 */
export function applyGrammar(skeleton, grammar) {
  if (!grammar || grammar.length === 0) return skeleton;
  const lines = parseLines(skeleton);
  /** index -> replacement lines, applied after the scan so indices stay valid. */
  const rewrites = [];

  for (let i = 0; i < lines.length; i += 1) {
    for (const region of grammar) {
      if (!matchesWrapper(lines[i].text, region.wrapper)) continue;

      const blocks = childBlocks(lines, i);

      // TUPLE REPETITION. The comparison grid repeats in GROUPS, not in items:
      // `rows.map()` returns a fragment emitting three flat sibling cells per
      // row, into the same grid that holds three header cells. Collapsing its
      // children one by one would describe a structure that does not exist.
      //
      // Deliberately NOT a generic "children divisible by N, probably rows"
      // heuristic — only a region that declares `tuple` is read this way.
      if (region.tuple) {
        // `lastShapes` is a SET, not one shape: the closing row inherits its
        // own cell branches, so a table ending in a text row and one ending in
        // a boolean row are both legitimate closings of the same grammar.
        const { prefix = 0, size, shapes, lastShapes } = region.tuple;
        const head = blocks.slice(0, prefix);
        const rest = blocks.slice(prefix);
        const indent2 = '  '.repeat(lines[i].depth + 1);

        // ARITY IS STRUCTURE. Leftovers are never truncated or ignored: a grid
        // with a missing or extra cell is a broken grid, and it must say so.
        if (rest.length === 0 || rest.length % size !== 0) continue;

        const groups = [];
        for (let g = 0; g < rest.length; g += size) {
          groups.push(rest.slice(g, g + size).map((b) => blockSkeleton(lines, b)).join('\n'));
        }

        const known = new Map(shapes.map((sh) => [sh.skeleton, sh.name]));
        const closing = new Map((lastShapes ?? []).map((sh) => [sh.skeleton, sh.name]));
        const isLast = (idx) => idx === groups.length - 1;
        const ok = groups.every((g, idx) => {
          // POSITION IS STRUCTURE TOO. A closing row is not merely another
          // permitted form — the closed corner belongs at the end. A closing
          // shape in the middle, or a plain one at the end, is a real defect.
          if (closing.size > 0) return isLast(idx) ? closing.has(g) : known.has(g);
          return known.has(g);
        });
        if (!ok) continue;

        // The fixed prefix keeps being compared verbatim — a changed, missing
        // or reordered header still fails.
        const headLines = head.flatMap((b) => blockSkeleton(lines, b).split('\n').map((l) => indent2 + l));
        const body = [...shapes]
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((sh) => `${indent2}TUPLE_REPEAT<${region.id}:${sh.name}>`);
        for (const sh of [...(lastShapes ?? [])].sort((a, b) => a.name.localeCompare(b.name))) {
          body.push(`${indent2}TUPLE_LAST<${region.id}:${sh.name}>`);
        }

        rewrites.push({
          from: blocks[0][0],
          to: blocks[blocks.length - 1][1],
          lines: [...headLines, ...body],
        });
        break;
      }
      const declared = [...region.shapes].sort((a, b) => a.name.localeCompare(b.name));
      const known = new Map(declared.map((s) => [s.skeleton, s.name]));

      // Every child must be a declared shape. One stranger and the whole
      // region is left alone — emitted verbatim, so the hash moves and the
      // difference is reported rather than absorbed.
      const opts = { relationalIds: region.relationalIds === true };
      const unknown = blocks.some((b) => !known.has(blockSkeleton(lines, b, opts)));
      if (unknown) continue;

      const indent = '  '.repeat(lines[i].depth + 1);
      const body = declared.map((s) => `${indent}${region.kind.toUpperCase()}<${region.id}:${s.name}>`);
      // An empty region is NOT the same shape as a populated one unless the
      // grammar says zero is a legitimate cardinality for it.
      const belowMin = blocks.length < (region.min ?? 0);
      const head = belowMin ? [`${indent}<UNDERFILLED ${region.id} n=${blocks.length}>`] : [];

      const from = blocks.length ? blocks[0][0] : i + 1;
      const to = blocks.length ? blocks[blocks.length - 1][1] : i + 1;
      rewrites.push({ from, to, lines: [...head, ...body] });
      break;
    }
  }

  if (rewrites.length === 0) return skeleton;

  rewrites.sort((a, b) => b.from - a.from);
  const out = lines.map((l) => '  '.repeat(l.depth) + l.text);
  for (const r of rewrites) out.splice(r.from, r.to - r.from, ...r.lines);
  return out.join('\n');
}


// ---------------------------------------------------------------------------
// CONTEXTUAL VALUE NORMALIZATION — a value that is DATA in one place and
// GEOMETRY in another.
// ---------------------------------------------------------------------------
//
// Some attributes carry a product fact rather than a design decision, but only
// in a specific component. `opacity` is the case that surfaced this: ui/Stars
// .astro renders each star as
//
//     <path opacity={fill === 0 ? 0.25 : fill} />
//
// so a rating of 4,9 emits `opacity="0.9000000000000004"` on the fifth star and
// 4,2 emits `opacity="0.2"`. Two products with different ratings hashed
// differently — and Stars renders seven or more times per page, so this alone
// made fingerprint(A) === fingerprint(B) impossible regardless of anything else.
//
// WHY NOT DROP `opacity` GLOBALLY. Elsewhere an opacity IS a design decision —
// a deliberately faded overlay is part of the composition, and a change to it
// should fail. A global rule would stop noticing that. So the exception is
// keyed on (ancestor, element, attribute), the narrowest context that
// identifies the dynamic value without capturing any other SVG on the page.
//
// EVERY RULE HERE NEEDS FOUR THINGS, and the Stars one has them: a context, a
// reason, a positive test (rating 4,9 vs 4,2 hash alike) and a structural
// control (the star count, the wrapper, the tag and the path geometry all
// still fail when changed). There is deliberately no
// DROP_ALL_NUMERIC_ATTRIBUTES here and there must never be one.

/**
 * `<div role="img">` with the inline-flex star row's own classes. Scoped to
 * Stars specifically: an `opacity` on any other element keeps its value and
 * keeps failing.
 */
export const CONTEXTUAL_VALUE_RULES = [
  {
    id: 'stars/fill',
    ancestor: { tag: 'div', attrs: { role: 'img' }, classes: ['inline-flex', 'gap-0.5'] },
    element: { tag: 'path', classes: ['text-gold'] },
    attr: 'opacity',
  },
  // MEDIA SLOT DIMENSIONS. `width`/`height` on a media slot are the ASSET's
  // intrinsic pixels — swap a 1200x1200 photo for a 1600x900 one and both
  // move, though nothing about the template did. The slot's real geometry is
  // expressed by its wrapper, its classes, its aspect-ratio (kept verbatim in
  // `style`) and its object-fit, none of which this touches.
  //
  // Scoped to the MEDIA slot signature only — an <img> anywhere else keeps its
  // dimensions and keeps failing, because outside a declared slot a size is a
  // decision somebody made about one image.
  //
  // The NAME survives, so removing width, or adding it where the slot had
  // none, still moves the hash. The real dimensions are not lost either: they
  // stay in the asset manifest, where they are metadata rather than design.
  //
  // THE SLOT SIGNATURE IS `object-cover` + `w-full`, taken from the real
  // builds rather than guessed. Three slots carry varying dimensions — the
  // hero image, the how-it-works MEDIA slot (714 vs 896) and the UGC strip
  // (four different widths) — and all three have both classes. The guarantee
  // seal (`mx-auto size-28`, always 112) has NEITHER, so it stays compared:
  // that 112 is a fixed design size, not an asset's intrinsic pixels.
  { id: 'media/intrinsic-width', element: { tag: '*', classes: ['object-cover', 'w-full'] }, attr: 'width' },
  { id: 'media/intrinsic-height', element: { tag: '*', classes: ['object-cover', 'w-full'] }, attr: 'height' },
];

/**
 * React `useId()` output, e.g. `_r17R_3_`. Anchored, so a hand-written group
 * name like `shipping-method` never matches.
 */
const REACT_USE_ID = /^_[rR][0-9a-z]*R?_[0-9a-z]*_$/;

/**
 * Canonicalizes radio-group names RELATIONALLY, not to a constant.
 *
 * `name` on a radio is build identity — it comes from useId() and renumbers
 * like the island `prefix` does — but it is ALSO the only thing that says
 * which radios belong together. Rewriting every one to `<react-id>` would
 * erase that: two groups accidentally fused into one, or one group split
 * across two names, would both hash as correct.
 *
 * So names are numbered by FIRST APPEARANCE. The concrete React id is
 * discarded; the grouping, the number of distinct groups, and any accidental
 * collision between them all survive.
 *
 * Only `input[type=radio]` whose value matches the React pattern is touched.
 * A semantic name is left exactly as written.
 */
export function canonicalizeRadioGroups(skeleton) {
  const seen = new Map();
  return skeleton
    .split('\n')
    .map((line) => {
      if (!/^\s*<input\b/.test(line) || !line.includes('type="radio"')) return line;
      const m = /\sname="([^"]*)"/.exec(line);
      if (!m || !REACT_USE_ID.test(m[1])) return line;
      if (!seen.has(m[1])) seen.set(m[1], `<radio-group-${seen.size + 1}>`);
      return line.replace(/(\sname)="[^"]*"/, `$1="${seen.get(m[1])}"`);
    })
    .join('\n');
}

/** Rewrites the VALUE of a contextual attribute, keeping the attribute itself. */
export function normalizeContextualValues(skeleton, rules = CONTEXTUAL_VALUE_RULES) {
  if (!rules || rules.length === 0) return skeleton;
  const lines = parseLines(skeleton);
  /** ancestor element line by depth, so a rule can ask what encloses a node. */
  const stack = [];

  const out = lines.map(({ text, depth }) => {
    stack.length = depth;
    stack[depth] = text;

    // EVERY matching rule is applied, not just the first. One element can
    // carry two dynamic values — a media slot has both `width` and `height` —
    // and stopping at the first match left the second one comparing an asset's
    // pixels as if they were layout.
    let rewritten = text;
    for (const rule of rules) {
      if (!matchesWrapper(text, rule.element)) continue;
      // `ancestor` is OPTIONAL: a rule whose element signature is already
      // unambiguous (a media slot's own classes) needs no enclosing context,
      // while `stars/fill` does — a bare `path.text-gold` is not enough to
      // know it is a star. `slice(0, depth)` because an element is not its
      // own ancestor.
      if (rule.ancestor && !stack.slice(0, depth).some((a) => a && matchesWrapper(a, rule.ancestor))) continue;
      // The NAME survives; only the value collapses. An added or removed
      // attribute therefore still moves the hash.
      rewritten = rewritten.replace(new RegExp(`(\\s${rule.attr})="[^"]*"`), `$1="<${rule.id}>"`);
    }
    return '  '.repeat(depth) + rewritten;
  });

  return out.join('\n');
}


/**
 * OPTIONAL SLOTS — a region the template declares that a given product may or
 * may not fill.
 *
 * THE PROBLEM THIS SOLVES. Product A has a featured testimonial and product B
 * has none, because B's reviews contain no `quote`. Both are correct, and
 * both use the same template — but one rendered a section the other did not,
 * so their skeletons could never match. Making the section required would
 * force inventing a testimonial to keep the structure; dropping it from the
 * hash entirely would stop protecting its insides.
 *
 * THE ANCHOR COMES FROM THE DECLARATION, NOT THE DOM. That is what makes this
 * work. A marker cannot be inserted "where the section isn't" by looking at
 * the HTML — there is nothing to look at. But the grammar already knows the
 * canonical sequence, so it knows the slot sits between `section#como-funciona`
 * and the UGC strip. Present or absent, the same marker lands in the same
 * place, and the two products agree.
 *
 * TWO anchors rather than "the anchor's next sibling", because Astro emits a
 * hydration <script> between the two sections. Bracketing the slot survives
 * anything the framework inserts, while still pinning the position exactly.
 *
 * WHAT STAYS PROTECTED, which is the whole point of not simply eliding it:
 *
 *   position  the region is only canonicalized where the grammar says it
 *             belongs. Found anywhere else — earlier, later, nested, twice —
 *             it is left verbatim and the hash moves.
 *   shape     its subtree must equal the declared canonical shape. A changed
 *             wrapper, class, spacing or child composition does not match, so
 *             it is left verbatim and the hash moves.
 *
 * WHAT IT DELIBERATELY DOES NOT DECIDE is whether this product SHOULD have
 * filled the slot. `capability === true` implying presence is a different
 * claim about data, asserted by the capability-binding contract.
 */
export function applyOptionalSlots(skeleton, slots) {
  if (!slots || slots.length === 0) return skeleton;
  const lines = parseLines(skeleton);
  const out = lines.map((l) => '  '.repeat(l.depth) + l.text);

  // Applied back-to-front so earlier indices stay valid.
  const edits = [];

  for (const slot of slots) {
    const openIdx = lines.findIndex((l) => matchesWrapper(l.text, slot.after));
    const closeIdx = lines.findIndex((l) => matchesWrapper(l.text, slot.before));
    // Either anchor missing means the page is not the shape this slot belongs
    // to. Leave it alone; it fails on its own terms.
    if (openIdx === -1 || closeIdx === -1 || closeIdx <= openIdx) continue;

    const depth = lines[closeIdx].depth;
    const found = [];
    for (let k = 0; k < lines.length; k += 1) {
      if (matchesWrapper(lines[k].text, slot.wrapper)) found.push(k);
    }
    // Outside its bracket, or more than once, is a MISPLACEMENT rather than an
    // optional absence — position is structure. Leave the page verbatim.
    if (found.length > 1) continue;
    if (found.length === 1 && (found[0] < openIdx || found[0] > closeIdx)) continue;

    const at = found.length === 1 ? found[0] : closeIdx;
    const here = found.length === 1;

    if (!here) {
      // ABSENT. No DOM is fabricated: the marker is inserted into the
      // canonical representation at the position the grammar declares.
      edits.push({ from: at, to: at, lines: ['  '.repeat(depth) + `OPTIONAL<${slot.id}>`] });
      continue;
    }

    // PRESENT. Its subtree must be exactly the declared shape.
    let end = at + 1;
    while (end < lines.length && lines[end].depth > depth) end += 1;
    const base = lines[at].depth;
    const observed = lines.slice(at, end).map((l) => '  '.repeat(l.depth - base) + l.text).join('\n');
    if (observed !== slot.shape) continue; // changed markup: left verbatim, hash moves

    edits.push({ from: at, to: end, lines: ['  '.repeat(depth) + `OPTIONAL<${slot.id}>`] });
  }

  edits.sort((a, b) => b.from - a.from);
  for (const e of edits) out.splice(e.from, e.to - e.from, ...e.lines);
  return out.join('\n');
}

/**
 * @param {string} html rendered page markup
 * @param {object[]} [grammar] declared repeatable/optional regions
 * @returns {{ skeleton: string, hash: string, elements: number }}
 */
export function structuralFingerprint(html, grammar, slots) {
  const skeleton = applyOptionalSlots(
    applyGrammar(canonicalizeRadioGroups(normalizeContextualValues(structuralSkeleton(html))), grammar),
    slots,
  );
  return {
    skeleton,
    hash: createHash('sha256').update(skeleton).digest('hex'),
    elements: skeleton ? skeleton.split('\n').length : 0,
  };
}

/**
 * Every declared region whose wrapper element is ON THE PAGE but whose
 * children matched no shape the grammar declares for it — left verbatim by
 * applyGrammar() rather than collapsed — plus every region collapsed but
 * BELOW the grammar's own declared minimum count.
 *
 * A VALIDATION SIGNAL, not a fingerprint concern. structuralFingerprint()
 * already reacts to either condition — verbatim markup and an <UNDERFILLED>
 * marker both move the hash — this only names WHICH region and WHY, for a
 * caller (Validation's structural gate) that wants to FAIL on it rather than
 * merely notice a hash it has no earlier reference to compare against.
 *
 * A region whose wrapper is absent altogether is NOT reported: that is a
 * legitimate absence (no reviews, no merchant, no featured quote), the exact
 * case OPTIONAL<...> and the `zero: 'optional-capability'` regions exist to
 * make ordinary. This function only speaks to a region that IS on the page
 * and does not fit the shape the seal says a Fixed page is allowed to have.
 *
 * WHY THIS RECOMPUTES ITS OWN SKELETON RATHER THAN TAKING structuralFingerprint()'s
 * OUTPUT. structuralFingerprint() runs applyOptionalSlots() ON TOP OF
 * applyGrammar()'s result (see below) — and an optional slot (OPTIONAL<ReviewsSection>
 * under V2/V3) matches its whole bracketed block, REPEAT<reviews/cards:...> and
 * REPEAT<reviews/dots:...> markers included, and replaces that entire block with
 * one outer marker. Those inner REPEAT<> substrings are real but TRANSIENT: they
 * exist right after applyGrammar() and are gone from the final, fully-collapsed
 * skeleton. A region search against the FINAL skeleton would misreport every
 * region living inside an optional slot as "uncollapsed" even when it collapsed
 * correctly — caught by hand against outputs/1005007345199501, a landing already
 * fully verified in an earlier session, before this function was ever wired into
 * a gate. So this asks applyGrammar() the same question structuralFingerprint()
 * does, but stops one step earlier, before any optional slot can swallow the
 * markers this function needs to see.
 *
 * @param {string} html rendered page markup
 * @param {object[]} grammar declared regions (e.g. FIXED_GRAMMAR_V3)
 * @returns {{ id: string, message: string }[]}
 */
export function collectUncollapsedRegions(html, grammar) {
  const rawSkeleton = structuralSkeleton(html);
  const rawLines = rawSkeleton.split('\n');
  const grammarSkeleton = applyGrammar(canonicalizeRadioGroups(normalizeContextualValues(rawSkeleton)), grammar);
  const findings = [];
  for (const region of grammar ?? []) {
    const wrapperPresent = rawLines.some((line) => matchesWrapper(line.trim(), region.wrapper));
    if (!wrapperPresent) continue; // legitimately absent — outside this check's concern

    if (grammarSkeleton.includes(`<UNDERFILLED ${region.id} `)) {
      findings.push({
        id: region.id,
        message: `${region.id} has fewer items than the grammar's declared minimum (min ${region.min ?? 0})`,
      });
      continue;
    }

    const markerPrefixes = region.tuple
      ? [`TUPLE_REPEAT<${region.id}:`, `TUPLE_LAST<${region.id}:`]
      : [`${String(region.kind).toUpperCase()}<${region.id}:`];
    const collapsed = markerPrefixes.some((prefix) => grammarSkeleton.includes(prefix));
    if (!collapsed) {
      findings.push({
        id: region.id,
        message: `${region.id} is on the page but its markup matches no shape the grammar declares for it`,
      });
    }
  }
  return findings;
}
