// STRUCTURAL FINGERPRINT — the invariant that makes "Fixed AstraVibe" fixed.
//
// Two landings generated by this repo must be the SAME PAGE with different
// product data in it. Not "similar", not "the same blocks": structurally
// identical. This module reduces rendered HTML to the part that must never
// vary and hashes it, so the claim is a test rather than an intention.
//
//   structuralFingerprint(htmlA).hash === structuralFingerprint(htmlB).hash
//
// WHY NOT JUST "DON'T RUN THE DESIGN AGENT". Because that is a promise about
// a flag, and a flag is not an invariant. Anyone can add a section, reorder
// two, or widen a container by hand, and nothing would notice. The fingerprint
// notices.
//
// PURE STRING WORK, NO DEPENDENCIES, NO DOM. admin/test runs its contract
// suites under vitest's `server` project, which is the plain `node`
// environment — there is no document there to parse into, and adding a parser
// dependency to satisfy a test is exactly the kind of thing agents.MD forbids.
// Astro emits well-formed markup, so a tokenizer is enough; content-contract
// .mjs sets the same precedent of a dependency-free contract module.
//
// ---------------------------------------------------------------------------
// THE CENTRAL DESIGN DECISION: CLASSES ARE NOT NORMALIZED. ALL OF THEM SURVIVE.
// ---------------------------------------------------------------------------
//
// The obvious-looking rule — "strip any class that carries a colour, because
// palette varies per product" — is WRONG here, and it is wrong in the most
// dangerous direction: it produces a false PASS. It cannot distinguish
// `bg-grape` (would be stripped) from `bg-white`, and a regex loose enough to
// catch colour words is loose enough to eat `bg-gradient-to-r`, which is
// layout.
//
// It is also unnecessary, and that is the real point. In this template the
// palette lives in CSS custom properties inside the `@theme` block of
// global.css — `--color-grape: #7C3AED`. Per-product recolouring rewrites
// THOSE VALUES. It does not rewrite the markup: `class="bg-grape"` is
// byte-identical in every product, because the token name never changes, only
// what it resolves to. The palette is simply not present in the HTML.
//
// So colour reaches the HTML through exactly two doors, and those are the only
// two this module closes: hex/rgb literals inside `style` attributes, and the
// same literals inside inline SVG paint attributes. Everything else about a
// class attribute — spacing, widths, grid, breakpoints, order, every
// responsive variant — is kept and compared.
//
// ---------------------------------------------------------------------------

import { createHash } from 'node:crypto';

/**
 * Attribute values that carry PRODUCT DATA rather than structure. The
 * attribute's presence is structural and is kept; its value is dropped.
 *
 * `href` is here because a link's destination is product/merchant data (a
 * Shopify handle, a legal page slug), while the fact that a link exists at
 * that position is structure. Same reasoning for every entry: keep the slot,
 * drop what is in it.
 */
export const VALUE_DROPPED_ATTRS = new Set([
  'href',
  'src',
  'srcset',
  'poster',
  'alt',
  'title',
  'content', // <meta content="..."> — description, og:*, theme-color
  'value',
  'placeholder',
  'aria-label',
  'aria-describedby',
  'aria-labelledby',
  'datetime',
  'download',
  'style', // handled specially below — declarations survive, values are filtered
]);

/**
 * Attributes dropped ENTIRELY, name included, because they are build-identity
 * rather than page structure.
 *
 * Astro stamps every island with a `uid` and content-hashed `component-url` /
 * `renderer-url`, and serialises the island's props into `props`. All four
 * change when the product changes or merely when the bundle is rebuilt.
 * `component-export` is deliberately NOT here: WHICH island is mounted at a
 * position is structure, and swapping CartDrawer for something else must fail.
 */
export const FULLY_DROPPED_ATTRS = new Set([
  'uid',
  'props',
  'component-url',
  'renderer-url',
  'ssr',
  'opts',
  'integrity',
  'nonce',
]);

/**
 * The media-slot signature, from ui/Media.astro.
 *
 * That component renders `<video>` when the product has a video for the slot
 * and `<img>` when it has a still, and BOTH carry this exact class triple plus
 * the same inline `aspect-ratio`. The slot's geometry is therefore already
 * invariant by construction — only the tag differs.
 *
 * Per the Fixed contract, "same visual slot geometry, adaptable media" means a
 * product with video and a product without must not be called structurally
 * different. So inside this signature the tag name collapses to MEDIA. The
 * aspect-ratio style is NOT collapsed: that IS the geometry, and a slot that
 * changes shape between products is a real regression.
 *
 * Scoped deliberately tight. An `<img>` anywhere else in the page is still
 * compared as an `<img>`, so a stray image added to a section still fails.
 */
export const MEDIA_SLOT_CLASSES = ['h-full', 'w-full', 'object-cover'];
const MEDIA_SLOT_TAGS = new Set(['img', 'video', 'picture', 'source']);

/**
 * Attributes that exist only because of WHICH media kind filled the slot, and
 * are therefore dropped name-and-all inside one.
 *
 * Collapsing the tag to MEDIA is not enough on its own: `<img>` brings `alt`
 * and `sizes`, `<video>` brings `poster`, `muted`, `loop` and friends, so two
 * slots holding the same geometry would still differ by the mere PRESENCE of
 * those names. That is the media kind leaking back in through the attribute
 * list, and it would fail a product whose only sin is having a video where
 * AstraVibe had a still.
 *
 * Scoped to media slots only. Outside one, `loading` and `decoding` stay
 * comparable, because there they describe a decision someone made about a
 * specific image rather than the shape of a slot.
 */
const MEDIA_SLOT_KIND_ATTRS = new Set([
  'alt', 'poster', 'sizes', 'widths', 'loading', 'decoding',
  'muted', 'loop', 'playsinline', 'autoplay', 'preload', 'controls', 'type',
]);

/**
 * `style` declarations whose VALUE is product data rather than geometry.
 *
 * Exactly one entry, and it earns its place: 13-real-results.astro draws each
 * rating bar as `style="width:{pct}%"`, so the number is a review statistic.
 * Every other inline declaration keeps its value, which is why an inline
 * `padding:12px` that appears in one product and not the other still fails.
 */
const DYNAMIC_STYLE_PROPS = new Set(['width']);

const VOID_TAGS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'param', 'source', 'track', 'wbr',
]);

/** Tags whose text content is never page structure. */
const RAW_TEXT_TAGS = new Set(['script', 'style', 'template', 'noscript']);

const COLOUR_LITERAL = /#[0-9a-f]{3,8}\b|\b(?:rgba?|hsla?|oklch|color-mix)\([^)]*\)/gi;

/** Collapses colour literals so a repaint never moves the fingerprint. */
function stripColours(value) {
  return value.replace(COLOUR_LITERAL, '<colour>');
}

/**
 * Reduces a `style` attribute to its declarations, keeping property names and
 * geometry values while removing colour and the one dynamic numeric property.
 */
function normalizeStyle(value) {
  return value
    .split(';')
    .map((decl) => decl.trim())
    .filter(Boolean)
    .map((decl) => {
      const colon = decl.indexOf(':');
      if (colon === -1) return decl;
      const prop = decl.slice(0, colon).trim().toLowerCase();
      const raw = decl.slice(colon + 1).trim();
      if (DYNAMIC_STYLE_PROPS.has(prop)) return `${prop}:<n>`;
      return `${prop}:${stripColours(raw)}`;
    })
    .sort() // declaration order is not layout
    .join(';');
}

/**
 * Astro island ids and Vite-hashed anchors are build identity. Page anchors —
 * #buy, #faq, #garantia, #como-funciona — are structure a reader can link to,
 * and losing one must fail.
 *
 * The rule is shape-based rather than a hardcoded anchor list, so a template
 * that adds a new anchor does not need this module edited: an id that is a
 * long unbroken hash-looking run is build output; anything with a hyphen or
 * short enough to be hand-written is an anchor.
 */
function normalizeId(value) {
  return /^[A-Za-z0-9_]{10,}$/.test(value) && /\d/.test(value) ? '<uid>' : value;
}

/** `class="b  a"` and `class="a b"` are the same styling; sort so they hash alike. */
function normalizeClass(value) {
  return value.split(/\s+/).filter(Boolean).sort().join(' ');
}

/**
 * Walks the raw markup and emits one line per element, indented by depth.
 * Text nodes, comments and doctype never appear: copy is the most dynamic
 * thing on the page.
 */
export function structuralSkeleton(html) {
  const lines = [];
  let depth = 0;
  let i = 0;

  while (i < html.length) {
    const lt = html.indexOf('<', i);
    if (lt === -1) break;

    // comment / doctype / CDATA — never structure
    if (html.startsWith('<!', lt)) {
      const end = html.indexOf('>', lt);
      i = end === -1 ? html.length : end + 1;
      continue;
    }

    const gt = findTagEnd(html, lt);
    if (gt === -1) break;
    const rawTag = html.slice(lt + 1, gt);
    i = gt + 1;

    if (rawTag.startsWith('/')) {
      depth = Math.max(0, depth - 1);
      continue;
    }

    const selfClosing = rawTag.endsWith('/');
    const tagBody = selfClosing ? rawTag.slice(0, -1) : rawTag;
    const nameMatch = /^([a-zA-Z][\w:-]*)/.exec(tagBody);
    if (!nameMatch) continue;

    const tag = nameMatch[1].toLowerCase();
    const attrs = parseAttrs(tagBody.slice(nameMatch[1].length));

    lines.push('  '.repeat(depth) + renderElement(tag, attrs));

    // Raw-text elements: skip to the matching close so their body is never
    // mistaken for markup. A `<script>` containing `<div>` is not a div.
    if (RAW_TEXT_TAGS.has(tag) && !selfClosing) {
      const close = html.toLowerCase().indexOf(`</${tag}`, i);
      i = close === -1 ? html.length : close;
      continue;
    }

    if (!selfClosing && !VOID_TAGS.has(tag)) depth += 1;
  }

  return lines.join('\n');
}

/** Finds the `>` that closes a tag, ignoring any inside a quoted value. */
function findTagEnd(html, start) {
  let quote = null;
  for (let j = start + 1; j < html.length; j += 1) {
    const ch = html[j];
    if (quote) {
      if (ch === quote) quote = null;
    } else if (ch === '"' || ch === "'") {
      quote = ch;
    } else if (ch === '>') {
      return j;
    }
  }
  return -1;
}

/** `name="v" flag name='v'` → ordered [name, value] pairs; bare flags get ''. */
function parseAttrs(source) {
  const attrs = [];
  const re = /([a-zA-Z_:@][\w:.@-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    attrs.push([m[1].toLowerCase(), m[2] ?? m[3] ?? m[4] ?? '']);
  }
  return attrs;
}

function renderElement(tag, attrs) {
  const classAttr = attrs.find(([name]) => name === 'class');
  const classes = classAttr ? classAttr[1].split(/\s+/).filter(Boolean) : [];

  const isMediaSlot =
    MEDIA_SLOT_TAGS.has(tag) && MEDIA_SLOT_CLASSES.every((c) => classes.includes(c));

  const parts = [];
  for (const [name, value] of attrs) {
    if (FULLY_DROPPED_ATTRS.has(name)) continue;
    if (isMediaSlot && MEDIA_SLOT_KIND_ATTRS.has(name)) continue;
    if (name === 'class') {
      parts.push(`class="${normalizeClass(value)}"`);
    } else if (name === 'id') {
      parts.push(`id="${normalizeId(value)}"`);
    } else if (name === 'style') {
      parts.push(`style="${normalizeStyle(value)}"`);
    } else if (VALUE_DROPPED_ATTRS.has(name)) {
      parts.push(name);
    } else if (name === 'fill' || name === 'stroke') {
      parts.push(`${name}="${stripColours(value)}"`);
    } else {
      parts.push(value === '' ? name : `${name}="${value}"`);
    }
  }

  parts.sort(); // attribute order is not structure
  return `<${isMediaSlot ? 'MEDIA' : tag}${parts.length ? ' ' + parts.join(' ') : ''}>`;
}

/**
 * @param {string} html rendered page markup
 * @returns {{ skeleton: string, hash: string, elements: number }}
 */
export function structuralFingerprint(html) {
  const skeleton = structuralSkeleton(html);
  return {
    skeleton,
    hash: createHash('sha256').update(skeleton).digest('hex'),
    elements: skeleton ? skeleton.split('\n').length : 0,
  };
}
