// STRUCTURAL FINGERPRINT — the invariant that makes "Fixed AstraVibe" fixed.
//
// Two landings generated by this repo must be the SAME PAGE with different
// product data in it. Not "similar", not "the same blocks": structurally
// identical. This module reduces rendered HTML to the part that must never
// vary and hashes it, so the claim is a test rather than an intention.
//
//   structuralFingerprint(htmlA).hash === structuralFingerprint(htmlB).hash
//
// WHY NOT JUST "DON'T RUN THE DESIGN AGENT". Because that is a promise about
// a flag, and a flag is not an invariant. Anyone can add a section, reorder
// two, or widen a container by hand, and nothing would notice. The fingerprint
// notices.
//
// PURE STRING WORK, NO DEPENDENCIES, NO DOM. admin/test runs its contract
// suites under vitest's `server` project, which is the plain `node`
// environment — there is no document there to parse into, and adding a parser
// dependency to satisfy a test is exactly the kind of thing agents.MD forbids.
// Astro emits well-formed markup, so a tokenizer is enough; content-contract
// .mjs sets the same precedent of a dependency-free contract module.
//
// ---------------------------------------------------------------------------
// THE CENTRAL DESIGN DECISION: CLASSES ARE NOT NORMALIZED. ALL OF THEM SURVIVE.
// ---------------------------------------------------------------------------
//
// The obvious-looking rule — "strip any class that carries a colour, because
// palette varies per product" — is WRONG here, and it is wrong in the most
// dangerous direction: it produces a false PASS. It cannot distinguish
// `bg-grape` (would be stripped) from `bg-white`, and a regex loose enough to
// catch colour words is loose enough to eat `bg-gradient-to-r`, which is
// layout.
//
// It is also unnecessary, and that is the real point. In this template the
// palette lives in CSS custom properties inside the `@theme` block of
// global.css — `--color-grape: #7C3AED`. Per-product recolouring rewrites
// THOSE VALUES. It does not rewrite the markup: `class="bg-grape"` is
// byte-identical in every product, because the token name never changes, only
// what it resolves to. The palette is simply not present in the HTML.
//
// So colour reaches the HTML through exactly two doors, and those are the only
// two this module closes: hex/rgb literals inside `style` attributes, and the
// same literals inside inline SVG paint attributes. Everything else about a
// class attribute — spacing, widths, grid, breakpoints, order, every
// responsive variant — is kept and compared.
//
// ---------------------------------------------------------------------------

import { createHash } from 'node:crypto';

/**
 * Attribute values that carry PRODUCT DATA rather than structure. The
 * attribute's presence is structural and is kept; its value is dropped.
 *
 * `href` is here because a link's destination is product/merchant data (a
 * Shopify handle, a legal page slug), while the fact that a link exists at
 * that position is structure. Same reasoning for every entry: keep the slot,
 * drop what is in it.
 */
export const VALUE_DROPPED_ATTRS = new Set([
  'href',
  'src',
  'srcset',
  'poster',
  'alt',
  'title',
  'content', // <meta content="..."> — description, og:*, theme-color
  'value',
  'placeholder',
  'aria-label',
  'aria-describedby',
  'aria-labelledby',
  'datetime',
  'download',
  'style', // handled specially below — declarations survive, values are filtered
]);

/**
 * Attributes dropped ENTIRELY, name included, because they are build-identity
 * rather than page structure.
 *
 * Astro stamps every island with a `uid` and content-hashed `component-url` /
 * `renderer-url`, and serialises the island's props into `props`. All four
 * change when the product changes or merely when the bundle is rebuilt.
 * `component-export` is deliberately NOT here: WHICH island is mounted at a
 * position is structure, and swapping CartDrawer for something else must fail.
 *
 * `prefix` joined them after an audit, not because it broke a hash. It is
 * Astro's per-render island counter (`r9`, `r10`, …): DETERMINISTIC — two
 * identical builds produce identical prefixes, verified by building twice —
 * but it renumbers when an earlier island appears or disappears, so a preview
 * build and a commerce build disagree on it for every island after the first
 * difference. It encodes render ORDER and nothing else, and order is already
 * carried by the skeleton's own sequence plus `component-export`. Dropping it
 * therefore hides no composition: a moved, swapped or removed island still
 * fails. See the control test in contract.fixed-fingerprint.test.ts.
 */
export const FULLY_DROPPED_ATTRS = new Set([
  'uid',
  'prefix',
  'props',
  'component-url',
  'renderer-url',
  'ssr',
  'opts',
  'integrity',
  'nonce',
]);

/**
 * The media-slot signature, from ui/Media.astro.
 *
 * That component renders `<video>` when the product has a video for the slot
 * and `<img>` when it has a still, and BOTH carry this exact class triple plus
 * the same inline `aspect-ratio`. The slot's geometry is therefore already
 * invariant by construction — only the tag differs.
 *
 * Per the Fixed contract, "same visual slot geometry, adaptable media" means a
 * product with video and a product without must not be called structurally
 * different. So inside this signature the tag name collapses to MEDIA. The
 * aspect-ratio style is NOT collapsed: that IS the geometry, and a slot that
 * changes shape between products is a real regression.
 *
 * Scoped deliberately tight. An `<img>` anywhere else in the page is still
 * compared as an `<img>`, so a stray image added to a section still fails.
 */
export const MEDIA_SLOT_CLASSES = ['h-full', 'w-full', 'object-cover'];
const MEDIA_SLOT_TAGS = new Set(['img', 'video', 'picture', 'source']);

/**
 * Attributes that exist only because of WHICH media kind filled the slot, and
 * are therefore dropped name-and-all inside one.
 *
 * Collapsing the tag to MEDIA is not enough on its own: `<img>` brings `alt`
 * and `sizes`, `<video>` brings `poster`, `muted`, `loop` and friends, so two
 * slots holding the same geometry would still differ by the mere PRESENCE of
 * those names. That is the media kind leaking back in through the attribute
 * list, and it would fail a product whose only sin is having a video where
 * AstraVibe had a still.
 *
 * Scoped to media slots only. Outside one, `loading` and `decoding` stay
 * comparable, because there they describe a decision someone made about a
 * specific image rather than the shape of a slot.
 */
const MEDIA_SLOT_KIND_ATTRS = new Set([
  'alt', 'poster', 'sizes', 'widths', 'loading', 'decoding',
  'muted', 'loop', 'playsinline', 'autoplay', 'preload', 'controls', 'type',
]);

/**
 * `style` declarations whose VALUE is product data rather than geometry.
 *
 * Exactly one entry, and it earns its place: 13-real-results.astro draws each
 * rating bar as `style="width:{pct}%"`, so the number is a review statistic.
 * Every other inline declaration keeps its value, which is why an inline
 * `padding:12px` that appears in one product and not the other still fails.
 */
const DYNAMIC_STYLE_PROPS = new Set(['width']);

const VOID_TAGS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'param', 'source', 'track', 'wbr',
]);

/** Tags whose text content is never page structure. */
const RAW_TEXT_TAGS = new Set(['script', 'style', 'template', 'noscript']);

const COLOUR_LITERAL = /#[0-9a-f]{3,8}\b|\b(?:rgba?|hsla?|oklch|color-mix)\([^)]*\)/gi;

/** Collapses colour literals so a repaint never moves the fingerprint. */
function stripColours(value) {
  return value.replace(COLOUR_LITERAL, '<colour>');
}

/**
 * Reduces a `style` attribute to its declarations, keeping property names and
 * geometry values while removing colour and the one dynamic numeric property.
 */
function normalizeStyle(value) {
  return value
    .split(';')
    .map((decl) => decl.trim())
    .filter(Boolean)
    .map((decl) => {
      const colon = decl.indexOf(':');
      if (colon === -1) return decl;
      const prop = decl.slice(0, colon).trim().toLowerCase();
      const raw = decl.slice(colon + 1).trim();
      if (DYNAMIC_STYLE_PROPS.has(prop)) return `${prop}:<n>`;
      return `${prop}:${stripColours(raw)}`;
    })
    .sort() // declaration order is not layout
    .join(';');
}

/**
 * Astro island ids and Vite-hashed anchors are build identity. Page anchors —
 * #buy, #faq, #garantia, #como-funciona — are structure a reader can link to,
 * and losing one must fail.
 *
 * The rule is shape-based rather than a hardcoded anchor list, so a template
 * that adds a new anchor does not need this module edited: an id that is a
 * long unbroken hash-looking run is build output; anything with a hyphen or
 * short enough to be hand-written is an anchor.
 */
function normalizeId(value) {
  return /^[A-Za-z0-9_]{10,}$/.test(value) && /\d/.test(value) ? '<uid>' : value;
}

/** `class="b  a"` and `class="a b"` are the same styling; sort so they hash alike. */
function normalizeClass(value) {
  return value.split(/\s+/).filter(Boolean).sort().join(' ');
}

/**
 * Walks the raw markup and emits one line per element, indented by depth.
 * Text nodes, comments and doctype never appear: copy is the most dynamic
 * thing on the page.
 */
export function structuralSkeleton(html) {
  const lines = [];
  let depth = 0;
  let i = 0;

  while (i < html.length) {
    const lt = html.indexOf('<', i);
    if (lt === -1) break;

    // comment / doctype / CDATA — never structure
    if (html.startsWith('<!', lt)) {
      const end = html.indexOf('>', lt);
      i = end === -1 ? html.length : end + 1;
      continue;
    }

    const gt = findTagEnd(html, lt);
    if (gt === -1) break;
    const rawTag = html.slice(lt + 1, gt);
    i = gt + 1;

    if (rawTag.startsWith('/')) {
      depth = Math.max(0, depth - 1);
      continue;
    }

    const selfClosing = rawTag.endsWith('/');
    const tagBody = selfClosing ? rawTag.slice(0, -1) : rawTag;
    const nameMatch = /^([a-zA-Z][\w:-]*)/.exec(tagBody);
    if (!nameMatch) continue;

    const tag = nameMatch[1].toLowerCase();
    const attrs = parseAttrs(tagBody.slice(nameMatch[1].length));

    lines.push('  '.repeat(depth) + renderElement(tag, attrs));

    // Raw-text elements: skip to the matching close so their body is never
    // mistaken for markup. A `<script>` containing `<div>` is not a div.
    if (RAW_TEXT_TAGS.has(tag) && !selfClosing) {
      const close = html.toLowerCase().indexOf(`</${tag}`, i);
      i = close === -1 ? html.length : close;
      continue;
    }

    if (!selfClosing && !VOID_TAGS.has(tag)) depth += 1;
  }

  return lines.join('\n');
}

/** Finds the `>` that closes a tag, ignoring any inside a quoted value. */
function findTagEnd(html, start) {
  let quote = null;
  for (let j = start + 1; j < html.length; j += 1) {
    const ch = html[j];
    if (quote) {
      if (ch === quote) quote = null;
    } else if (ch === '"' || ch === "'") {
      quote = ch;
    } else if (ch === '>') {
      return j;
    }
  }
  return -1;
}

/** `name="v" flag name='v'` → ordered [name, value] pairs; bare flags get ''. */
function parseAttrs(source) {
  const attrs = [];
  const re = /([a-zA-Z_:@][\w:.@-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    attrs.push([m[1].toLowerCase(), m[2] ?? m[3] ?? m[4] ?? '']);
  }
  return attrs;
}

function renderElement(tag, attrs) {
  const classAttr = attrs.find(([name]) => name === 'class');
  const classes = classAttr ? classAttr[1].split(/\s+/).filter(Boolean) : [];

  const isMediaSlot =
    MEDIA_SLOT_TAGS.has(tag) && MEDIA_SLOT_CLASSES.every((c) => classes.includes(c));

  const parts = [];
  for (const [name, value] of attrs) {
    if (FULLY_DROPPED_ATTRS.has(name)) continue;
    if (isMediaSlot && MEDIA_SLOT_KIND_ATTRS.has(name)) continue;
    if (name === 'class') {
      parts.push(`class="${normalizeClass(value)}"`);
    } else if (name === 'id') {
      parts.push(`id="${normalizeId(value)}"`);
    } else if (name === 'style') {
      parts.push(`style="${normalizeStyle(value)}"`);
    } else if (VALUE_DROPPED_ATTRS.has(name)) {
      parts.push(name);
    } else if (name === 'fill' || name === 'stroke') {
      parts.push(`${name}="${stripColours(value)}"`);
    } else {
      parts.push(value === '' ? name : `${name}="${value}"`);
    }
  }

  parts.sort(); // attribute order is not structure
  return `<${isMediaSlot ? 'MEDIA' : tag}${parts.length ? ' ' + parts.join(' ') : ''}>`;
}


// ---------------------------------------------------------------------------
// REPEATABLE AND OPTIONAL REGIONS — structural GRAMMAR, not rendered instance.
// ---------------------------------------------------------------------------
//
// THE PROBLEM THIS SOLVES. A gallery with four images and a gallery with eight
// are the same design. The skeleton disagreed, because it recorded one line per
// rendered element, so element COUNT — which follows array LENGTH — was being
// compared as if it were layout. Two products of the same template could never
// hash alike unless their data happened to be the same size.
//
// WHAT IT IS NOT. There is no heuristic here: nothing detects "similar
// siblings" and collapses them. A region is normalized ONLY if an explicit
// entry in the grammar names its wrapper, and only into the item shapes that
// entry declares. A blanket sibling-collapse would hide the regressions this
// module exists to catch.
//
// THE EMISSION IS THE DECLARATION, NOT THE OBSERVATION. A region emits every
// shape its grammar declares, sorted, whether or not this particular build
// rendered one. That is what lets a product whose variants are all in stock
// hash identically to one with a sold-out variant: both use the same grammar,
// and WHICH states occurred is data. Coverage of the declared shapes is proved
// separately, by tests that materialize each one — see the state-coverage
// suite. A shape nobody can produce must not sit in the grammar unexercised.
//
// THREE THINGS KEEP IT SAFE:
//
//   1. The WRAPPER's own line is emitted exactly as before. Change its classes,
//      its grid, its breakpoint or its role and the hash moves — only its
//      CHILDREN are abstracted.
//   2. An item whose sub-skeleton is not among the declared shapes is emitted
//      VERBATIM. Changed card markup, a new child type or a swapped component
//      therefore still fails, loudly.
//   3. A region declared `min` that renders fewer items emits a distinct
//      marker, so an empty wrapper never hashes as a full one.
//
// OPTIONAL regions work the same way and answer a different question: a slot
// the template declares may legitimately not materialize, because a capability
// is absent. `OPTIONAL<Shape>` says the template HAS that slot. Whether this
// product filled it is a capability fact, reported separately and never folded
// into this hash. Absence is only ever normalized for a registered optional
// region — a section that vanishes without one is still a failure.

/** Splits a skeleton into `[line, depth]` pairs. Indent is two spaces per level. */
function parseLines(skeleton) {
  return skeleton.split('\n').filter(Boolean).map((line) => {
    const body = line.replace(/^ +/, '');
    return { text: body, depth: (line.length - body.length) / 2 };
  });
}

/** The direct-child blocks of the element at `index`, each as `[from, to)`. */
function childBlocks(lines, index) {
  const parentDepth = lines[index].depth;
  const blocks = [];
  let i = index + 1;
  while (i < lines.length && lines[i].depth > parentDepth) {
    if (lines[i].depth === parentDepth + 1) {
      const start = i;
      i += 1;
      while (i < lines.length && lines[i].depth > parentDepth + 1) i += 1;
      blocks.push([start, i]);
    } else {
      i += 1;
    }
  }
  return blocks;
}

/** A child block rendered as its own skeleton, re-indented from zero. */
function blockSkeleton(lines, [from, to]) {
  const base = lines[from].depth;
  return lines
    .slice(from, to)
    .map((l) => '  '.repeat(l.depth - base) + l.text)
    .join('\n');
}

/** Does this element line satisfy a grammar entry's wrapper matcher? */
function matchesWrapper(text, wrapper) {
  if (!text.startsWith(`<${wrapper.tag}`) && wrapper.tag !== '*') return false;
  for (const cls of wrapper.classes ?? []) {
    // Classes are sorted and space-joined by normalizeClass, so a word-boundary
    // test is exact without depending on their order.
    if (!new RegExp(`(^|[" ])${cls.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}([" ]|$)`).test(text)) return false;
  }
  for (const [name, value] of Object.entries(wrapper.attrs ?? {})) {
    if (!text.includes(value === true ? ` ${name}` : ` ${name}="${value}"`)) return false;
  }
  return true;
}

/**
 * Rewrites declared regions into their grammar. Returns the skeleton unchanged
 * when no grammar is supplied, so every existing caller keeps its behaviour.
 */
export function applyGrammar(skeleton, grammar) {
  if (!grammar || grammar.length === 0) return skeleton;
  const lines = parseLines(skeleton);
  /** index -> replacement lines, applied after the scan so indices stay valid. */
  const rewrites = [];

  for (let i = 0; i < lines.length; i += 1) {
    for (const region of grammar) {
      if (!matchesWrapper(lines[i].text, region.wrapper)) continue;

      const blocks = childBlocks(lines, i);
      const declared = [...region.shapes].sort((a, b) => a.name.localeCompare(b.name));
      const known = new Map(declared.map((s) => [s.skeleton, s.name]));

      // Every child must be a declared shape. One stranger and the whole
      // region is left alone — emitted verbatim, so the hash moves and the
      // difference is reported rather than absorbed.
      const unknown = blocks.some((b) => !known.has(blockSkeleton(lines, b)));
      if (unknown) continue;

      const indent = '  '.repeat(lines[i].depth + 1);
      const body = declared.map((s) => `${indent}${region.kind.toUpperCase()}<${region.id}:${s.name}>`);
      // An empty region is NOT the same shape as a populated one unless the
      // grammar says zero is a legitimate cardinality for it.
      const belowMin = blocks.length < (region.min ?? 0);
      const head = belowMin ? [`${indent}<UNDERFILLED ${region.id} n=${blocks.length}>`] : [];

      const from = blocks.length ? blocks[0][0] : i + 1;
      const to = blocks.length ? blocks[blocks.length - 1][1] : i + 1;
      rewrites.push({ from, to, lines: [...head, ...body] });
      break;
    }
  }

  if (rewrites.length === 0) return skeleton;

  rewrites.sort((a, b) => b.from - a.from);
  const out = lines.map((l) => '  '.repeat(l.depth) + l.text);
  for (const r of rewrites) out.splice(r.from, r.to - r.from, ...r.lines);
  return out.join('\n');
}


// ---------------------------------------------------------------------------
// CONTEXTUAL VALUE NORMALIZATION — a value that is DATA in one place and
// GEOMETRY in another.
// ---------------------------------------------------------------------------
//
// Some attributes carry a product fact rather than a design decision, but only
// in a specific component. `opacity` is the case that surfaced this: ui/Stars
// .astro renders each star as
//
//     <path opacity={fill === 0 ? 0.25 : fill} />
//
// so a rating of 4,9 emits `opacity="0.9000000000000004"` on the fifth star and
// 4,2 emits `opacity="0.2"`. Two products with different ratings hashed
// differently — and Stars renders seven or more times per page, so this alone
// made fingerprint(A) === fingerprint(B) impossible regardless of anything else.
//
// WHY NOT DROP `opacity` GLOBALLY. Elsewhere an opacity IS a design decision —
// a deliberately faded overlay is part of the composition, and a change to it
// should fail. A global rule would stop noticing that. So the exception is
// keyed on (ancestor, element, attribute), the narrowest context that
// identifies the dynamic value without capturing any other SVG on the page.
//
// EVERY RULE HERE NEEDS FOUR THINGS, and the Stars one has them: a context, a
// reason, a positive test (rating 4,9 vs 4,2 hash alike) and a structural
// control (the star count, the wrapper, the tag and the path geometry all
// still fail when changed). There is deliberately no
// DROP_ALL_NUMERIC_ATTRIBUTES here and there must never be one.

/**
 * `<div role="img">` with the inline-flex star row's own classes. Scoped to
 * Stars specifically: an `opacity` on any other element keeps its value and
 * keeps failing.
 */
export const CONTEXTUAL_VALUE_RULES = [
  {
    id: 'stars/fill',
    ancestor: { tag: 'div', attrs: { role: 'img' }, classes: ['inline-flex', 'gap-0.5'] },
    element: { tag: 'path', classes: ['text-gold'] },
    attr: 'opacity',
  },
];

/** Rewrites the VALUE of a contextual attribute, keeping the attribute itself. */
export function normalizeContextualValues(skeleton, rules = CONTEXTUAL_VALUE_RULES) {
  if (!rules || rules.length === 0) return skeleton;
  const lines = parseLines(skeleton);
  /** ancestor element line by depth, so a rule can ask what encloses a node. */
  const stack = [];

  const out = lines.map(({ text, depth }) => {
    stack.length = depth;
    stack[depth] = text;

    for (const rule of rules) {
      if (!matchesWrapper(text, rule.element)) continue;
      // `slice(0, depth)` — the element cannot be its own ancestor.
      if (!stack.slice(0, depth).some((a) => a && matchesWrapper(a, rule.ancestor))) continue;
      // The NAME survives; only the value collapses. An added or removed
      // opacity attribute therefore still moves the hash.
      const rewritten = text.replace(
        new RegExp(`(\\s${rule.attr})="[^"]*"`),
        `$1="<${rule.id}>"`,
      );
      return '  '.repeat(depth) + rewritten;
    }
    return '  '.repeat(depth) + text;
  });

  return out.join('\n');
}

/**
 * @param {string} html rendered page markup
 * @param {object[]} [grammar] declared repeatable/optional regions
 * @returns {{ skeleton: string, hash: string, elements: number }}
 */
export function structuralFingerprint(html, grammar) {
  const skeleton = applyGrammar(normalizeContextualValues(structuralSkeleton(html)), grammar);
  return {
    skeleton,
    hash: createHash('sha256').update(skeleton).digest('hex'),
    elements: skeleton ? skeleton.split('\n').length : 0,
  };
}
